import Feladatok
# Feladatok.elsoFeladat()
# Feladatok.masodikFeladat()
# Feladatok.harmadikFeladat()
# Feladatok.negyedikFeladat()
# Feladatok.otodikFeladat()
# Feladatok.hatodikFeladat()
# Feladatok.hetedikFeladat()
# Feladatok.nyolcadikFeladat()
Feladatok.kilencedikFeladat()